### ISSUE TITLE
Case sensitivity in MySQL

### ISSUE THREAD

**Issue by gransabr** [BatteryAcid/dayz-private-server-aws#10]
https://github.com/BatteryAcid/dayz-private-server-aws/wiki/3-dayz-database-setup

There you mention some find/replace which I did but it was not enough sadly. I was still unable to spin the Arma server because of errors such as "table character_DATA not found" (my wording) because the actual table in question is called (lowercase) "character_data" for some reason. I suspect there would be a lot of other similar issues so after some googling of a more system solution I have changed another MySQL param on RDS:

lower_case_table_names

and set it to "1".

More info: https://stackoverflow.com/questions/11165944/how-to-change-mysql-table-names-in-linux-server-to-be-case-insensitive

The Arma server was then able to start fine. I did not have time to thoroughly check if everything is working as it should but when I logged off my character and logged back in, everything was as it should be.

I am not saying this is a truly correct and long-term working solution but it did help me for now.

**Comment by BatteryAcid** [comment]
Hmm, as far as I can tell I've never ran into that, but the `pCleanup.sql` does contain the text `character_DATA`, so maybe that's the cause.  That cleanup script runs periodically and probably at startup.  

Not sure why these tables names are all over the place but it's definitely going to cause issues.  I've captured all the 1.8.9 SQL files in this parent repo, so we could just make the fix there.

**Comment by gransabr** [comment]
Thank you for your reply.

Before I did the "lower_case_table_names" change, I have tried manually fixing the character_DATA string in the SQL files which helped but only to get stuck on yet another similar error and I suspect it would be full of these going forward so I wanted a more system solution instead.

Changing the SQL files manually works too but you would need to do that for every upcoming version of DayZ mod probably. I understand there wont be a lot of them anymore but still... Middle ground would be to write some automation (JS?) for this repo that would take the mod files and built the corrected files into some gitignored folder on user request.

**Comment by BatteryAcid** [comment]
Follow up question - which operation system are you using to run the MySQL scripts on?  Are you running them locally from a Mac or PC?  Or some other way?

**Comment by gransabr** [comment]
I am simply using the same EC2 Windows instance for the server install/maintenance, not just to run the server. I like it all together at one place like that. I think I only had to install old version of the MySQL dump tool to be compatible with the Dayz database otherwise it would not be able to dump a manual ".sql" backup files (which is what I am doing instead of RDS backups for now for testing only).
