### ISSUE TITLE
SUGGESTION: Folder structure in c:\ drive root

### ISSUE THREAD

**Issue by gransabr** [BatteryAcid/dayz-private-server-aws#11]
The folder structure in c:\ drive root could perhaps be reworked to have as much editable files in one folder as possible. That way I could easily open the whole folder in a code editor and do global search/replace etc. In current situation I would need to open the whole c:\ drive which is not ideal. I hope you know what I mean now. Just a little detail though so dont worry about it too much :)

**Comment by BatteryAcid** [comment]
Do mean combining the `c:\cfgdayz\` and `c:\servertools` into a single directory?

**Comment by gransabr** [comment]
Perhaps but sorry, it was a rookie suggestion, after some time playing with the server I think anyone will do it as they see fit anyway, so the current structure is just fine for a quick start :) You can just close this one as far as I am concerned.

Thank you!

**Comment by gransabr** [comment]
By the way, on the note that everyone will do it as they see fit, I have actually installed Epoch there now and it works fine. Now I think the purpose of this repo should remain more about AWS rather than about an ideal installation of Dayz mod as that is already reasonably covered elsewhere. Instructions for the most basic Dayz mod installation are just enough I think, to see if it runs and then everyone can go their own way with the mod itself I guess.

**Comment by BatteryAcid** [comment]
I think it's definitely worth the time trying to hash out a decent strategy for some of the more minor details.  It provides a starting point and helps keep things organized in reference to the guide.
